# ---
# repos:
# - repo: https://github.com/pre-commit/mirrors-clang-tidy
# rev: v17.0.6
# hooks:
#   - id: clang-tidy
#     files: ^(.*[.]cpp|.*[.]h)$
#     args: ["-checks=*", "-warnings-as-errors=*"]
# - repo: https://github.com/ssciwr/clang-format-hook
#   rev: v14.0.0
#   hooks:
#     - id: clang-format
#       files: ^(.*[.]cpp|.*[.]h)$
#       args: ["--style=file", "-i"]
# - repo: https://github.com/cpplint/cpplint
#   rev: 1.6.0
#   hooks:
#     - id: cpplint
#       files: ^(.*[.]cpp|.*[.]h)$
#       args: ["--filter=-legal/copyright,-build/header_guard,-readability/todo,-whitespace/indent,-build/c++11,-runtime/references"]
# - repo: https://github.com/pocc/pre-commit-hooks
#   rev: 9a9bbc00895bbdb7670231c2565d4f1309c42905
#   hooks:
#     - id: cppcheck
#       files: ^(.*[.]cpp|.*[.]h)$
#       args: ["--inline-suppr", "--enable=all", "--suppress=missingIncludeSystem", "--suppress=missingInclude", "--suppress=unusedFunction", "--suppress=unmatchedSuppression", "--suppress=unusedStructMember", "--language=c++", "--std=c++20", "--error-exitcode=1"]

repos:
- repo: https://github.com/ssciwr/clang-format-hook
  rev: v14.0.0
  hooks:
    - id: clang-format
      files: ^(.*[.]cpp|.*[.]h)$
      args: ["--style=file", "-i"]
- repo: https://github.com/cpplint/cpplint
  rev: 1.6.0
  hooks:
    - id: cpplint
      files: ^(.*[.]cpp|.*[.]h)$
      args: ["--filter=-legal/copyright,-build/header_guard,-readability/todo,-whitespace/indent,-build/c++11,-runtime/references,-build/include_order,-whitespace/blank_line"]
- repo: https://github.com/pocc/pre-commit-hooks
  rev: 9a9bbc00895bbdb7670231c2565d4f1309c42905
  hooks:
    - id: cppcheck
      files: ^(.*[.]cpp|.*[.]h)$
      args: ["--inline-suppr", "--enable=all", "--suppress=missingIncludeSystem", "--suppress=missingInclude", "--suppress=unusedFunction", "--suppress=unmatchedSuppression", "--suppress=unusedStructMember", "--language=c++", "--std=c++20", "--error-exitcode=1"]
