map_name: Forest
background: "../resources/backgrounds/nuke.png"
tile_width: 32
tile_height: 32
planting_spots: 16
blocks:
  - x: 32
    y: 64
    type: Common
    texture: "../resources/tiles/grass1.png"
  - x: 96
    y: 128
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 160
    y: 192
    type: Plantable
    texture: "../resources/tiles/plantspot.png"
  - x: 128
    y: 384
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 96
    y: 416
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 96
    y: 448
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 96
    y: 288
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 32
    y: 352
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 64
    y: 384
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 128
    y: 352
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 224
    y: 288
    type: Solid
    texture: "../resources/tiles/solid1.png"
  - x: 96
    y: 256
    type: Solid
    texture: "../resources/tiles/solid8.png"
  - x: 128
    y: 256
    type: Common
    texture: "../resources/tiles/grass2.png"
  - x: 160
    y: 256
    type: Solid
    texture: "../resources/tiles/woodenbox1.png"
  - x: 128
    y: 288
    type: Solid
    texture: "../resources/tiles/woodenbox1.png"
  - x: 160
    y: 288
    type: Solid
    texture: "../resources/tiles/woodenbox1.png"
  - x: 128
    y: 320
    type: Solid
    texture: "../resources/tiles/woodenbox1.png"
  - x: 256
    y: 416
    type: TSpawn
    texture: "../resources/tiles/tspawn.png"
  - x: 224
    y: 384
    type: CtSpawn
    texture: "../resources/tiles/ctspawn.png"
  - x: 288
    y: 320
    type: Plantable
    texture: "../resources/tiles/sitea.png"
  - x: 256
    y: 288
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 352
    y: 288
    type: Solid
    texture: "../resources/tiles/solid8.png"
  - x: 448
    y: 320
    type: Solid
    texture: "../resources/tiles/solid8.png"
  - x: 512
    y: 416
    type: Solid
    texture: "../resources/tiles/solid8.png"
  - x: 544
    y: 448
    type: Solid
    texture: "../resources/tiles/solid8.png"
  - x: 544
    y: 512
    type: Solid
    texture: "../resources/tiles/solid8.png"
  - x: 544
    y: 544
    type: Solid
    texture: "../resources/tiles/solid8.png"
  - x: 0
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 32
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 64
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 96
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 128
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 160
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 192
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 224
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 256
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 320
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 352
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 384
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
  - x: 288
    y: 0
    type: Plantable
    texture: "../resources/tiles/siteb.png"
