background: ../resources/backgrounds/nuke.png
planting_spots: 2
blocks:
  - x: 96
    y: 224
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 128
    y: 224
    type: Solid
    texture: ../resources/tiles/woodenbox5.png
  - x: 160
    y: 224
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 96
    y: 192
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 128
    y: 192
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 160
    y: 192
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 192
    y: 224
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 192
    y: 192
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 96
    y: 256
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 128
    y: 256
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 160
    y: 256
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 192
    y: 256
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 64
    y: 256
    type: Solid
    texture: ../resources/tiles/solid2.png
  - x: 64
    y: 224
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 64
    y: 192
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 64
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 96
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 128
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 160
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 192
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 128
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 256
    y: 224
    type: Plantable
    texture: ../resources/tiles/siteb.png
  - x: 96
    y: 288
    type: Common
    texture: ../resources/tiles/sandgrass1.png
  - x: 128
    y: 288
    type: Common
    texture: ../resources/tiles/sandgrass1.png
  - x: 160
    y: 288
    type: Common
    texture: ../resources/tiles/sandgrass1.png
  - x: 192
    y: 288
    type: Common
    texture: ../resources/tiles/sandgrass1.png
  - x: 224
    y: 288
    type: Common
    texture: ../resources/tiles/sandgrass1.png
  - x: 224
    y: 256
    type: Common
    texture: ../resources/tiles/sandgrass1.png
  - x: 224
    y: 224
    type: Common
    texture: ../resources/tiles/sandgrass1.png
  - x: 224
    y: 192
    type: Common
    texture: ../resources/tiles/sandgrass1.png
  - x: 64
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 64
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 224
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 256
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 160
    y: 320
    type: CtSpawn
    texture: ../resources/tiles/ctspawn.png
  - x: 192
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 224
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 256
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 256
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 256
    y: 256
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 160
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 192
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 256
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 288
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 224
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 288
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 288
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 288
    y: 256
    type: Common
    texture: ../resources/tiles/gravel3.png
  - x: 128
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 96
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 288
    y: 224
    type: Common
    texture: ../resources/tiles/gravel3.png
  - x: 288
    y: 192
    type: Common
    texture: ../resources/tiles/gravel3.png
  - x: 96
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 256
    y: 192
    type: TSpawn
    texture: ../resources/tiles/tspawn.png
  - x: 64
    y: 352
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 64
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 128
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 160
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 224
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 256
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 192
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 96
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 288
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 320
    y: 384
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 320
    y: 352
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 320
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 320
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 320
    y: 256
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 320
    y: 224
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 320
    y: 192
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 320
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 288
    y: 160
    type: Solid
    texture: ../resources/tiles/solid7.png
  - x: 32
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 32
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 352
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 352
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 384
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 384
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 416
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 416
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 448
    y: 320
    type: Solid
    texture: ../resources/tiles/woodenbox1.png
  - x: 416
    y: 256
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 448
    y: 256
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 448
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 416
    y: 224
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 448
    y: 224
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 448
    y: 192
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 416
    y: 192
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 416
    y: 160
    type: Plantable
    texture: ../resources/tiles/sitea.png
  - x: 448
    y: 160
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 448
    y: 128
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 416
    y: 128
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 384
    y: 256
    type: Common
    texture: ../resources/tiles/sandpath4.png
  - x: 384
    y: 224
    type: Common
    texture: ../resources/tiles/sandpath4.png
  - x: 384
    y: 192
    type: Common
    texture: ../resources/tiles/sandpath4.png
  - x: 384
    y: 160
    type: Common
    texture: ../resources/tiles/sandpath4.png
  - x: 384
    y: 128
    type: Common
    texture: ../resources/tiles/sandpath4.png
  - x: 352
    y: 256
    type: Solid
    texture: ../resources/tiles/solid1.png
  - x: 480
    y: 256
    type: Common
    texture: ../resources/tiles/sandpath2.png
  - x: 480
    y: 224
    type: Common
    texture: ../resources/tiles/sandpath2.png
  - x: 480
    y: 192
    type: Common
    texture: ../resources/tiles/sandpath2.png
  - x: 480
    y: 160
    type: Common
    texture: ../resources/tiles/sandpath2.png
  - x: 480
    y: 128
    type: Common
    texture: ../resources/tiles/sandpath2.png
  - x: 416
    y: 96
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 448
    y: 96
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 416
    y: 352
    type: Common
    texture: ../resources/tiles/sandgravel1.png
  - x: 448
    y: 352
    type: Common
    texture: ../resources/tiles/sandgravel2.png
  - x: 416
    y: 384
    type: Common
    texture: ../resources/tiles/gravel3.png
  - x: 416
    y: 416
    type: Common
    texture: ../resources/tiles/gravel3.png
  - x: 448
    y: 416
    type: Common
    texture: ../resources/tiles/gravel3.png
  - x: 448
    y: 384
    type: Common
    texture: ../resources/tiles/gravel3.png
  - x: 416
    y: 448
    type: Common
    texture: ../resources/tiles/sandgravel3.png
  - x: 448
    y: 448
    type: Common
    texture: ../resources/tiles/sandgravel4.png
  - x: 384
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 384
    y: 416
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 384
    y: 448
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 384
    y: 384
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 480
    y: 448
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 480
    y: 416
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 480
    y: 384
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 480
    y: 352
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 480
    y: 320
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 480
    y: 288
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 480
    y: 96
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 32
    y: 256
    type: Solid
    texture: ../resources/tiles/solid1.png
  - x: 0
    y: 256
    type: Solid
    texture: ../resources/tiles/solid1.png
  - x: 0
    y: 288
    type: Solid
    texture: ../resources/tiles/solid1.png
  - x: 0
    y: 320
    type: Solid
    texture: ../resources/tiles/solid1.png
  - x: 0
    y: 352
    type: Solid
    texture: ../resources/tiles/solid1.png
  - x: 32
    y: 352
    type: Solid
    texture: ../resources/tiles/solid1.png
  - x: 352
    y: 352
    type: Solid
    texture: ../resources/tiles/solid1.png
  - x: 384
    y: 96
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 352
    y: 96
    type: Solid
    texture: ../resources/tiles/woodenbox1.png
  - x: 352
    y: 64
    type: Solid
    texture: ../resources/tiles/woodenbox1.png
  - x: 384
    y: 64
    type: Solid
    texture: ../resources/tiles/woodenbox5.png
  - x: 480
    y: 64
    type: Solid
    texture: ../resources/tiles/woodenbox5.png
  - x: 512
    y: 64
    type: Solid
    texture: ../resources/tiles/woodenbox1.png
  - x: 512
    y: 96
    type: Solid
    texture: ../resources/tiles/woodenbox1.png
  - x: 416
    y: 64
    type: Common
    texture: ../resources/tiles/sand1.png
  - x: 448
    y: 64
    type: Common
    texture: ../resources/tiles/sand1.png