tilesheet: "resources/embrador.bmp"
tile_width: 32
tile_height: 32
rows: 12
cols: 8
blocks:
  # Fila 0 (y=0)
  - x: 0
    y: 0
    texture: "purple"
    type: "Unknown"
  - x: 1
    y: 0
    texture: "solid1"
    type: "Solid"
  - x: 2
    y: 0
    texture: "solid2"
    type: "Solid"
  - x: 3
    y: 0
    texture: "solid3"
    type: "Solid"
  - x: 4
    y: 0
    texture: "solid4"
    type: "Solid"
  - x: 5
    y: 0
    texture: "solid5"
    type: "Solid"
  - x: 6
    y: 0
    texture: "solid6"
    type: "Solid"
  - x: 7
    y: 0
    texture: "solid7"
    type: "Solid"

  # Fila 1 (y=1)
  - x: 0
    y: 1
    texture: "sand1"
    type: "Common"
  - x: 1
    y: 1
    texture: "sand2"
    type: "Common"
  - x: 2
    y: 1
    texture: "sand3"
    type: "Common"
  - x: 3
    y: 1
    texture: "sand4"
    type: "Common"
  - x: 4
    y: 1
    texture: "sand5"
    type: "Common"
  - x: 5
    y: 1
    texture: "sand6"
    type: "Common"
  - x: 6
    y: 1
    texture: "sand7"
    type: "Common"
  - x: 7
    y: 1
    texture: "sand8"
    type: "Common"

  # Fila 2 (y=2)
  - x: 0
    y: 2
    texture: "sand9"
    type: "Common"
  - x: 1
    y: 2
    texture: "path1"
    type: "Common"
  - x: 2
    y: 2
    texture: "path2"
    type: "Common"
  - x: 3
    y: 2
    texture: "grass1"
    type: "Common"
  - x: 4
    y: 2
    texture: "woodenbox1"
    type: "Solid"
  - x: 5
    y: 2
    texture: "solid8"
    type: "Solid"
  - x: 6
    y: 2
    texture: "grass2"
    type: "Common"
  - x: 7
    y: 2
    texture: "grass3"
    type: "Common"

  # Fila 3 (y=3)
  - x: 0
    y: 3
    texture: "sandgrass1"
    type: "Common"
  - x: 1
    y: 3
    texture: "sandgrass2"
    type: "Common"
  - x: 2
    y: 3
    texture: "sandgrass3"
    type: "Common"
  - x: 3
    y: 3
    texture: "sandgrass4"
    type: "Common"
  - x: 4
    y: 3
    texture: "sandgravel1"
    type: "Common"
  - x: 5
    y: 3
    texture: "sandgravel2"
    type: "Common"
  - x: 6
    y: 3
    texture: "sandgravel3"
    type: "Common"
  - x: 7
    y: 3
    texture: "sandgravel4"
    type: "Common"

  # Fila 4 (y=4)
  - x: 0
    y: 4
    texture: "gravel1"
    type: "Common"
  - x: 1
    y: 4
    texture: "gravel2"
    type: "Common"
  - x: 2
    y: 4
    texture: "gravel3"
    type: "Common"
  - x: 3
    y: 4
    texture: "sand10"
    type: "Common"
  - x: 4
    y: 4
    texture: "sand11"
    type: "Common"
  - x: 5
    y: 4
    texture: "sand12"
    type: "Common"
  - x: 6
    y: 4
    texture: "sand13"
    type: "Common"
  - x: 7
    y: 4
    texture: "grass4"
    type: "Common"

  # Fila 5 (y=5)
  - x: 0
    y: 5
    texture: "sandpath1"
    type: "Common"
  - x: 1
    y: 5
    texture: "sandpath2"
    type: "Common"
  - x: 2
    y: 5
    texture: "sandpath3"
    type: "Common"
  - x: 3
    y: 5
    texture: "sandpath4"
    type: "Common"
  - x: 4
    y: 5
    texture: "path3"
    type: "Common"
  - x: 5
    y: 5
    texture: "path4"
    type: "Common"
  - x: 6
    y: 5
    texture: "path5"
    type: "Common"
  - x: 7
    y: 5
    texture: "path6"
    type: "Common"

  # Fila 6 (y=6)
  - x: 0
    y: 6
    texture: "grass5"
    type: "Common"
  - x: 1
    y: 6
    texture: "grass6"
    type: "Common"
  - x: 2
    y: 6
    texture: "grass7"
    type: "Common"
  - x: 3
    y: 6
    texture: "grass8"
    type: "Common"
  - x: 4
    y: 6
    texture: "grass9"
    type: "Common"
  - x: 5
    y: 6
    texture: "grass10"
    type: "Common"
  - x: 6
    y: 6
    texture: "grass11"
    type: "Common"
  - x: 7
    y: 6
    texture: "solid9"
    type: "Solid"

  # Fila 7 (y=7)
  - x: 0
    y: 7
    texture: "sandgrass5"
    type: "Common"
  - x: 1
    y: 7
    texture: "grass12"
    type: "Common"
  - x: 2
    y: 7
    texture: "woodenbox2"
    type: "Solid"
  - x: 3
    y: 7
    texture: "woodenbox3"
    type: "Solid"
  - x: 4
    y: 7
    texture: "grass13"
    type: "Common"
  - x: 5
    y: 7
    texture: "grass14"
    type: "Common"
  - x: 6
    y: 7
    texture: "path7"
    type: "Common"
  - x: 7
    y: 7
    texture: "plantspot2"
    type: "Plantable"

  # Fila 8 (y=8)
  - x: 0
    y: 8
    texture: "woodenbox4"
    type: "Solid"
  - x: 1
    y: 8
    texture: "woodenbox5"
    type: "Solid"
  - x: 2
    y: 8
    texture: "woodenbox6"
    type: "Solid"
  - x: 3
    y: 8
    texture: "ctspawn"
    type: "CtSpawn"
  - x: 4
    y: 8
    texture: "tspawn"
    type: "TSpawn"
  - x: 5
    y: 8
    texture: "plantspot1"
    type: "Plantable"
  - x: 6
    y: 8
    texture: "sitea"
    type: "Plantable"
  - x: 7
    y: 8
    texture: "siteb"
    type: "Plantable"

  # Fila 9 (y=9)
  - x: 0
    y: 9
    texture: "floor1"
    type: "Common"
  - x: 1
    y: 9
    texture: "floor2"
    type: "Common"
  - x: 2
    y: 9
    texture: "floor3"
    type: "Common"
  - x: 3
    y: 9
    texture: "floor4"
    type: "Common"
  - x: 4
    y: 9
    texture: "floor5"
    type: "Common"
  - x: 5
    y: 9
    texture: "floor6"
    type: "Common"
  - x: 6
    y: 9
    texture: "floor7"
    type: "Common"
  - x: 7
    y: 9
    texture: "none1"
    type: "Common"

  # Fila 10 (y=10)
  - x: 0
    y: 10
    texture: "floor8"
    type: "Common"
  - x: 1
    y: 10
    texture: "floor9"
    type: "Common"
  - x: 2
    y: 10
    texture: "floor10"
    type: "Common"
  - x: 3
    y: 10
    texture: "floor11"
    type: "Common"
  - x: 4
    y: 10
    texture: "floor12"
    type: "Common"
  - x: 5
    y: 10
    texture: "floor13"
    type: "Common"
  - x: 6
    y: 10
    texture: "floor14"
    type: "Common"
  - x: 7
    y: 10
    texture: "floor15"
    type: "Common"

  # Fila 11 (y=11)
  - x: 0
    y: 11
    texture: "none2"
    type: "Common"
  - x: 1
    y: 11
    texture: "floor16"
    type: "Common"
  - x: 2
    y: 11
    texture: "floor17"
    type: "Common"
  - x: 3
    y: 11
    texture: "floor18"
    type: "Common"
  - x: 4
    y: 11
    texture: "floor19"
    type: "Common"
  - x: 5
    y: 11
    texture: "floor20"
    type: "Common"
  - x: 6
    y: 11
    texture: "floor21"
    type: "Common"
  - x: 7
    y: 11
    texture: "floor22"
    type: "Common"