tilesheet: "../resources/weapons.bmp"
tile_width: 32
tile_height: 32
rows: 1
cols: 4
blocks:
  # Fila 0 (y=0)
  - x: 0
    y: 0
    texture: "../resources/weapons/glock.png"
    type: "DropedGlock"
  - x: 1
    y: 0
    texture: "../resources/weapons/ak47.png"
    type: "DropedAk47"
  - x: 2
    y: 0
    texture: "../resources/weapons/m4.png"
    type: "DropedM4"
  - x: 3
    y: 0
    texture: "../resources/weapons/awp.png"
    type: "DropedAwp"