tilesheet: "resources/weapons.bmp"
tile_width: 32
tile_height: 32
rows: 1
cols: 4
blocks:
  # Fila 0 (y=0)
  - x: 0
    y: 0
    texture: "glock"
    type: "DropedGlock"
  - x: 1
    y: 0
    texture: "ak47"
    type: "DropedAk47"
  - x: 2
    y: 0
    texture: "m4"
    type: "DropedM4"
  - x: 3
    y: 0
    texture: "awp"
    type: "DropedAwp"