background: "../resources/backgrounds/blood.jpg"
planting_spots: 1
blocks:
  - x: 32
    y: 64
    type: Common
    texture: "../resources/tiles/tile_12.png"
  - x: 96
    y: 128
    type: Solid
    texture: "../resources/tiles/tile_26.png"
  - x: 160
    y: 192
    type: Plantable
    texture: "../resources/tiles/tile_44.png"
  - x: 128
    y: 384
    type: Solid
    texture: "../resources/tiles/tile_36.png"
  - x: 96
    y: 416
    type: Solid
    texture: "../resources/tiles/tile_63.png"
  - x: 96
    y: 448
    type: Solid
    texture: "../resources/tiles/tile_62.png"
  - x: 96
    y: 288
    type: Solid
    texture: "../resources/tiles/tile_71.png"
  - x: 32
    y: 352
    type: Solid
    texture: "../resources/tiles/tile_70.png"
  - x: 64
    y: 384
    type: Solid
    texture: "../resources/tiles/tile_71.png"
  - x: 128
    y: 352
    type: Solid
    texture: "../resources/tiles/tile_69.png"
  - x: 224
    y: 288
    type: Solid
    texture: "../resources/tiles/tile_62.png"
  - x: 256
    y: 224
    type: Common
    texture: "../resources/tiles/tile_20.png"
  - x: 256
    y: 288
    type: Common
    texture: "../resources/tiles/tile_27.png"
  - x: 192
    y: 384
    type: Common
    texture: "../resources/tiles/tile_51.png"
  - x: 288
    y: 480
    type: Common
    texture: "../resources/tiles/tile_62.png"
  - x: 256
    y: 448
    type: Common
    texture: "../resources/tiles/tile_70.png"
  - x: 160
    y: 288
    type: Common
    texture: "../resources/tiles/tile_71.png"
  - x: 64
    y: 192
    type: Common
    texture: "../resources/tiles/tile_70.png"
  - x: 0
    y: 256
    type: Common
    texture: "../resources/tiles/tile_71.png"
  - x: 32
    y: 480
    type: Common
    texture: "../resources/tiles/tile_70.png"