name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libopus-dev \
            libopusfile-dev \
            libxmp-dev \
            libfluidsynth-dev \
            fluidsynth \
            libwavpack1 \
            libwavpack-dev \
            libfreetype-dev \
            wavpack \
            libsdl2-dev \
            libsdl2-image-dev

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          make -j$(nproc)

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

